name: Release master on semantic version change
on:
  push:
    branches:
      - master

env:
  PACKAGES_ACCESS_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}

jobs:
  release_master:
    name: Release master
    permissions:
      checks: write
      contents: write
      packages: write

    runs-on:
      - ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: temurin
          cache: gradle

      - uses: gradle/actions/setup-gradle@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - run: ./gradlew test

      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          files: ./build/test-results/test/*.xml

      - run: npm install

      - run: npm audit signatures

      - run: npx semantic-release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
